# -*- coding: utf-8 -*-
"""studymatee

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jWu2F18_HB0WVqNYbHYYTfRqzEhsAmfz
"""

!pip install gradio huggingface_hub pypdf

from huggingface_hub import InferenceClient
import gradio as gr
import os
from pypdf import PdfReader

# Set your HuggingFace API key
os.environ["HF_API_KEY"] = "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"

# Select a stable HuggingFace model
client = InferenceClient(
    model="meta-llama/Meta-Llama-3-8B-Instruct",
    token=os.environ["HF_API_KEY"]
)

def generate_text(prompt):
    response = client.text_generation(
        prompt,
        max_new_tokens=400,
        temperature=0.7,
    )
    return response

def extract_pdf_text(pdf_file):
    reader = PdfReader(pdf_file)
    text = ""
    for page in reader.pages:
        content = page.extract_text()
        if content:
            text += content + "\n"
    return text

def generate_multilang_qa(pdf, language):
    text = extract_pdf_text(pdf)

    prompt = f"""
    Generate 10 Question–Answer pairs from the following PDF content.
    Output language: {language}

    PDF Content:
    {text}
    """

    return generate_text(prompt)

def summarize_pdf(pdf):
    text = extract_pdf_text(pdf)

    prompt = f"""
    Provide a detailed, structured, easy-to-understand summary of the following PDF content:

    {text}
    """

    return generate_text(prompt)

def generate_quiz(pdf):
    text = extract_pdf_text(pdf)

    prompt = f"""
    Create a 10-question multiple-choice quiz based ONLY on this PDF content.
    Include 4 options for each question and mention the correct answer.

    PDF Content:
    {text}
    """

    return generate_text(prompt)

with gr.Blocks() as app:
    gr.Markdown("# 📘 LEARN — Study Mate (AI PDF Assistant)")

    with gr.Tab("🌍 Multi-language Q/A Generator"):
        pdf1 = gr.File(label="Upload PDF")
        lang = gr.Dropdown(
            ["English", "Hindi", "Tamil", "Telugu", "Kannada", "Malayalam", "French", "Spanish", "Arabic"],
            label="Select Language"
        )
        qa_output = gr.Textbox(label="Generated Q/A", lines=12)
        gr.Button("Generate Q/A").click(generate_multilang_qa, [pdf1, lang], qa_output)

    with gr.Tab("📝 Detailed PDF Summary"):
        pdf2 = gr.File(label="Upload PDF")
        summary_output = gr.Textbox(label="Detailed Summary", lines=12)
        gr.Button("Generate Summary").click(summarize_pdf, pdf2, summary_output)

    with gr.Tab("🧪 Quiz Generator"):
        pdf3 = gr.File(label="Upload PDF")
        quiz_output = gr.Textbox(label="Generated Quiz", lines=12)
        gr.Button("Generate Quiz").click(generate_quiz, pdf3, quiz_output)

app.launch()